### ISSUE TITLE
Changing default border color

### ISSUE THREAD

**Issue by nickmaio** [MrBartusek/gif-picker-react#30]
Would be nice to have a prop to easily replace default highlighting border color - the default blue one is great but, certainly, not suitable for all UI cases...

**Comment by MrBartusek** [comment]
You can change this using CSS varables like so:

Add this to your main CSS file (App.css, index.css or similar)
```css
.GifPickerReact {
  --gpr-highlight-color: red;
}
```
